name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: your-docker-image-name
      volumes:
        - /home/runner/.m2:/usr/share/maven/ref/repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: /usr/share/maven/ref/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and test
        run: mvn clean package